### ISSUE TITLE
change ip address graylog server - readonly file

### ISSUE THREAD

**Issue by raymondkops** [tonellotto/Distributed-Enabling-Platforms#5]
Hello I am not used to unix editors and permissions. I have read the documentation how th change the ip address for the graylog server. I need to change the interfaces file from dhcp to static. I cannot make the changes since the file is read only. If I change the permissions of the file (i found it on google) the file gets deleted and I am not able to create a new file. Could some tell me how the save the interfaces file,please ? I am logging in with the ubuntu user account as described in the documentation.

Thank you very much in advance !
kind regards

**Comment by raymondkops** [comment]
WHy is my issue closed ? It is still a valid problem !

Met vriendelijke groet / Mit freundlichen Grüßen / Kind regards,



Raymond Kops
Manager Automatisering



T

+31 180637613<+31%20180637613>

M

+31 622450421<+31%20622450421>

E

R.Kops@dznet.nl<mailto:R.Kops@dznet.nl>



[DEKKER - stijlvol in uw interieur]<http://www.dekkerzevenhuizen.nl/>





[FB]<https://www.facebook.com/dekkerzevenhuizenbv#!/dekkerzevenhuizenbv>

[PIN]<https://www.pinterest.com/dekkerinterieur/>

[TW]<https://twitter.com/DekkerInterieur>

[LI]<https://www.linkedin.com/company/481275?trk=tyah&trkInfo=tarId%3A1423583728765%2Ctas%3Adekker%20zevenhuizen%2Cidx%3A1-1-1>

[YT]<https://www.youtube.com/user/DekkerZevenhuizen>

[G+]<https://plus.google.com/s/dekker%20zevenhuizen#s/dekker%20zevenhuizen>



Van: Nicola Tonellotto [mailto:notifications@github.com]
Verzonden: maandag 30 november 2015 13:57
Aan: tonellotto/Distributed-Enabling-Platforms
CC: Raymond Kops
Onderwerp: Re: [Distributed-Enabling-Platforms] change ip address graylog server - readonly file (#5)


Closed #5<https://github.com/tonellotto/Distributed-Enabling-Platforms/issues/5>.

**Comment by tonellotto** [comment]
This is not an issues related to the code. Actually i do not know what are speaking about when you cite greylog server.
